version: '3.8'

services:
  app:
    container_name: app
    build: .
    image: samir9556/npm_ts_v1
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
      - PORT=${PORT}
      - IP=${IP}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
